### ISSUE TITLE
AD7124 Schematic

### ISSUE THREAD

**Issue by davepreiss** [NHBSystems/NHB_AD7124#2]
Hello, is the schematic used for the feather breakout for the AD7124 (linked below) available? I will be adapting for the Teensy 4.0 and would like to make sure I am breaking everything out correctly.

https://www.tindie.com/products/24680/

Thanks for the great library!

**Comment by jjuliano77** [comment]
Hi Dave, the design files can now be found in this repo: [AD7124-4-FeatherWing-PCB](https://github.com/NHBSystems/AD7124-4-FeatherWing-PCB). I've been meaning to put them up for a while now, thanks for the reminder.

**Comment by davepreiss** [comment]
Thanks for this great documentation and posting it so quickly!

I noticed that the flowmeter dual bridge example on page 77 of the datasheet, uses AVDD as an excitation source (still retaining the ability to switch off the bridges with PSW) and then using REFIN1+ and REFIN1- to reference to AVDD and AVSS respectively. Are there downsides to this approach in terms of noise etc? I can imagine it is very helpful to be able to swap to different excitation voltages by swapping to different ADR45XXs.

**Comment by jjuliano77** [comment]
I had a couple reasons for using an external regulator, but it certainly isn't necessary. Using AVDD for excitation would work just fine as long as you keep your digital stuff reasonably separated and have decent bypass caps. 

One potential issue that comes to mind is that if you use AVDD, and a sensor lead gets shorted, you may bring down your whole circuit. With a separate regulator, the rest of your application should be able keep running (assuming the reg has short protection). I wanted to be able to use my design in the field, so the extra isolation was nice (You wouldn't believe what I've seen people do to my sensor cables out the field). Depending on your use case, this may not be a concern.
